const { Objekt } = require('./Objekt')
const konstructor = require('./konstructor')
const { Mirror, mirrors } = require('./Mirror')
const Chars = require('./Chars')
const funktion = require('./funktion')
const { history, Lineage } = require('./utils')
const klass = require('./klass')
const Tree = require('./Tree')

exports.Objekt = Objekt
exports.konstructor = konstructor
exports.Mirror = Mirror
exports.mirrors = mirrors
exports.Chars = Chars
exports.funktion = funktion
exports.history = history
exports.Lineage = Lineage
exports.klass = klass
exports.Tree = Tree